[package]
name = "lean-matrix-analysis"
version = "0.1"
lean_version = "leanprover-community/lean:3.38.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "dfca2b0fb95497099e2edd0b4b19f281beb680b7"}
