[package]
name = "lean-matrix-analysis"
version = "0.1"
lean_version = "leanprover-community/lean:3.38.0"
path = "src"

[dependencies]
<<<<<<< HEAD
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cdad11046d5b66138327423c101147dc4119e252"}
=======
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "41811cdd82492ce0d1118114023ed4028d5953af"}
>>>>>>> 435b8409ac8e60ce250c670c5db37c13e8621f3b
